import type { RoomDefinition, RoomId } from "./types";

export const rooms: Record<RoomId, RoomDefinition> = {
  "grand-hall": {
    id: "grand-hall",
    name: "Team Hub",
    eyebrow: "The project workspace",
    connections: [
      "library",
      "map-room",
      "workshop",
      "conservatory",
      "observatory",
      "archivists-outer-office",
      "hall-of-reflections",
      "archivists-study",
    ],
    initiallyUnlocked: true,
  },
  library: {
    id: "library",
    name: "Docs Room",
    eyebrow: "Your first assignment",
    connections: ["grand-hall"],
    initiallyUnlocked: true,
  },
  "map-room": {
    id: "map-room",
    name: "System Map",
    eyebrow: "Waiting for codebase context",
    connections: ["grand-hall"],
    initiallyUnlocked: false,
  },
  workshop: {
    id: "workshop",
    name: "Build Lab",
    eyebrow: "The build needs investigation",
    connections: ["grand-hall"],
    initiallyUnlocked: false,
  },
  conservatory: {
    id: "conservatory",
    name: "Release Cycle",
    eyebrow: "Timing and dependencies matter",
    connections: ["grand-hall"],
    initiallyUnlocked: false,
  },
  observatory: {
    id: "observatory",
    name: "Pattern Review",
    eyebrow: "Runtime behavior needs explanation",
    connections: ["grand-hall"],
    initiallyUnlocked: false,
  },
  "archivists-outer-office": {
    id: "archivists-outer-office",
    name: "Team Lead’s Office",
    eyebrow: "A communication problem needs correction",
    connections: ["grand-hall", "hall-of-reflections"],
    initiallyUnlocked: false,
  },
  "hall-of-reflections": {
    id: "hall-of-reflections",
    name: "QA Review",
    eyebrow: "Compare intention with experience",
    connections: ["grand-hall"],
    initiallyUnlocked: false,
  },
  "archivists-study": {
    id: "archivists-study",
    name: "The Debrief Room",
    eyebrow: "The project is ready to reflect on",
    connections: ["grand-hall"],
    initiallyUnlocked: false,
  },
};
